### ISSUE TITLE
Skooma in minitest failed on minitest.rb:42:in `initialize'

### ISSUE THREAD

**Issue by artyomlagun** [skryukov/skooma#33]
I've added `skooma` in Gemfile, added configurations into test_helper.rb 
```ruby
# test_helper.rb

require 'skooma'
require 'skooma/minitest'
...other configs...
class ActionDispatch::IntegrationTest
  # API Documentation
  # To enable coverage, pass `coverage: :report` option,
  # and to raise an error when an operation is not covered, pass `coverage: :strict` option:
  path_to_openapi = Rails.root.join("public", "docs", "openapi.yml")
  include Skooma::Minitest[path_to_openapi, coverage: :report]
end
```
and when I started integration test (without any skooma's helpers in it), I got an error:
```ruby
bundle exec rails test ./test/integration/api/v2/boxes_test.rb:10
Coverage report generated for Integration Tests to /platform/coverage. 88 / 16287 LOC (0.54%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
/usr/local/bundle/gems/skooma-0.3.2/lib/skooma/minitest.rb:42:in `initialize': undefined method `after_run' for MiniTest:Module (NoMethodError)

      MiniTest.after_run { coverage.report }
              ^^^^^^^^^^
        from /platform/test/test_helper.rb:109:in `new'
        from /platform/test/test_helper.rb:109:in `<class:IntegrationTest>'
        from /platform/test/test_helper.rb:100:in `<main>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /platform/test/integration/api/v2/boxes_test.rb:1:in `<main>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/bundle/gems/railties-7.1.3.3/lib/rails/test_unit/runner.rb:51:in `block in load_tests'
        from /usr/local/bundle/gems/railties-7.1.3.3/lib/rails/test_unit/runner.rb:51:in `each'
        from /usr/local/bundle/gems/railties-7.1.3.3/lib/rails/test_unit/runner.rb:51:in `load_tests'
        from /usr/local/bundle/gems/railties-7.1.3.3/lib/rails/test_unit/runner.rb:43:in `run'
        from /usr/local/bundle/gems/railties-7.1.3.3/lib/rails/commands/test/test_command.rb:33:in `perform'
        from /usr/local/bundle/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
        from /usr/local/bundle/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/railties-7.1.3.3/lib/rails/command/base.rb:178:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
        from /usr/local/bundle/gems/railties-7.1.3.3/lib/rails/command/base.rb:73:in `perform'
        from /usr/local/bundle/gems/railties-7.1.3.3/lib/rails/command.rb:71:in `block in invoke'
        from /usr/local/bundle/gems/railties-7.1.3.3/lib/rails/command.rb:149:in `with_argv'
        from /usr/local/bundle/gems/railties-7.1.3.3/lib/rails/command.rb:69:in `invoke'
        from /usr/local/bundle/gems/railties-7.1.3.3/lib/rails/commands.rb:18:in `<main>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
 ```
  
could you say what did I do wrong? 
I'm using minitest (5.23.1) and skooma (0.3.2)

**Comment by skryukov** [comment]
@artyomlagun thanks for the issue, the fix is released in v0.3.3!
